### ISSUE TITLE
Does not work with the new version of the GOG SDK

### ISSUE THREAD

**Issue by TERNOX** [YoYoGames/GMEXT-GOG#3]
`[GOG] ERROR: Invalid GOG SDK version, sha256 hash mismatch (expected v1.150).`

Older versions are not available on the site

**Comment by TERNOX** [comment]
@DiasFranciscoA Thanks! Because now it's delaying my gog release.

**Comment by DiasFranciscoA** [comment]
We just checked that the older versions are still available on the site, and the new version doesn't have any fixes worth the update at the moment. Thank you so much for the report we will still consider the SDK update at a later time.

**Comment by nkrapivin** [comment]
Hi TERNOX, I made a PR that fixes several memory leaks and upgrades the SDK to the very latest version available right now on the DevPortal. Sadly I can't upgrade the dylibs as I don't own a Mac, but you can try taking the prebuilt Windows version from the sample project and see if that works for you.
(Tell Xitilon hi for me)

**Comment by TERNOX** [comment]
Thank you!
(I told it)

**Comment by nkrapivin** [comment]
Force pushed the PR once again to SDK 1.152.6, both Win and Mac are now updated.

**Comment by DiasFranciscoA** [comment]
CLOSED: PR #4 
Release will be updated soon
